### ISSUE TITLE
feat: Implement motor API

### ISSUE THREAD

**Issue by Ghaadyy** [Ghaadyy/elevator-controller#7]
### Suggested solution

This API should provide basic functionalities to manipulate the motor.
For example it should provide functions like `goto_floor(x)` which will move the _physical elevator cabin_ to the specific floor, without any overhead.

It should also provide a task that monitors the speed change switches and modify the motor's speed accordingly.

**Comment by A-Karam20** [comment]
The motor api should also communicate with the floor display api to know whether to go down or up

**Comment by Ghaadyy** [comment]
> The motor api should also communicate with the floor display api to know whether to go down or up

This will be implemented in #8.

**Comment by Ghaadyy** [comment]
> This will be implemented in #8.

It has been successfully implemented.
